CarDealers/Areas/Admin/Controllers/CarImagesController.cs
using Azure.Core;
using CarDealers.Areas.Admin.Models.CarViewModel;
using CarDealers.Entity;
using CarDealers.Models;
using CarDealers.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Emit;
using System.Threading;

namespace CarDealers.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin/[controller]/[action]")]
    public class CarImagesController : CustomController
    {
        int carid;
        //create dbContext variable
        private readonly CarDealersContext _context;

        public int Carid { get => carid; set => carid = value; }

        public CarImagesController(CarDealersContext context)
        {
            _context = context;
            authorizedRoles = new string[] { Constant.ADMIN_ROLE };
        }

        public IActionResult ListCarImages(int? page,int id)
        {
            if (!HasAuthorized())
            {
                return RedirectBaseOnPage();
            }

            int pageSize = 5; // Set the number of records per page
            int pageNumber = (page ?? 1); // If no page number is specified, default to 1

            //fetch data from database table orders
            var listCarImages = _context.ImageCars.Where(x => x.DeleteFlag == false&&x.CarId==id).Include(x => x.Car)
            .OrderBy(p => p.ImageId)
            .Skip((pageNumber - 1) * pageSize)
            .Take(pageSize).ToList();
            Carid = id;
            // Pass the records and page information to the view
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalRecords = _context.ImageCars.Where(x => x.DeleteFlag == false).Count();
            ViewBag.IdCar=id;
            return View(listCarImages);
        }



        public ActionResult CreateCarImages(int id)
        {
            Carid = id;
            ViewBag.CarId = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCarImages(int carId, List<IFormFile> ImageCars)
        {
            
            var imageCars = _context.ImageCars.Where(x => x.DeleteFlag == false).ToList();

            foreach (var imageFile in ImageCars)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Generate a unique file name for the image
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(imageFile.FileName);

                    // Combine the constant folder path and file name
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), Constant.PATH + Constant.IMAGELISTCAR, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await imageFile.CopyToAsync(fileStream);
                    }

                    var imageCar = new ImageCar
                    {
                        CarId = carId,
                        Image = Path.Combine(Constant.IMAGELISTCAR, fileName).Replace('\\', '/') // Store the file path in the database
                    };

                    await _context.ImageCars.AddAsync(imageCar);
                }
            }

            await _context.SaveChangesAsync();
            Carid = carId;
            return RedirectToAction("ListCarImages", new { page = 1, id = carId });
            //return RedirectToAction("ListCarImages");
        }



        [HttpGet]
        public IActionResult DeleteCarImages(int id)
        {
            if (ModelState.IsValid)
            {
                var carImages = _context.ImageCars.Where(x => x.ImageId == id).FirstOrDefault();
                carImages.DeleteFlag = true;
                _context.ImageCars.Update(carImages);
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListCarImages", new { page = 1, id = Carid });
        }


        [HttpGet]
        public ActionResult UpdateCarImages(int id)
        {
            if (ModelState.IsValid)
            {
                var carImages = _context.ImageCars.Where(x => x.ImageId == id && x.DeleteFlag == false).FirstOrDefault();

                if (carImages == null)
                {
                    return RedirectToAction("RecordNotFound");
                }
                return View(carImages);
            }
            return RedirectToAction("RecordNotFound");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UpdateCarImages(ImageCar model, IFormFile? ImageCars)
        {

            var imageCars = _context.ImageCars.Where(x => x.DeleteFlag == false).ToList();
            var CarImages = imageCars.Where(x => x.ImageId == model.ImageId).FirstOrDefault();

            if (CarImages == null)
            {
                return RedirectToAction("RecordNotFound");
            }

            CarImages.CarId = model.CarId;
            if (ImageCars != null && ImageCars.Length > 0)
            {
                // Delete the image file
                if (!string.IsNullOrEmpty(CarImages.Image))
                {
                    var imagePath = Path.Combine(Constant.PATH, CarImages.Image);
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                }
                // Generate a unique file name for the image
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(ImageCars.FileName);

                // Combine the constant folder path and file name
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), Constant.PATH + Constant.IMAGELISTCAR, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageCars.CopyToAsync(fileStream);
                }

                CarImages.Image = Path.Combine(Constant.IMAGELISTCAR, fileName).Replace('\\', '/'); // Store the file path in the database
            }

            _context.ImageCars.Update(CarImages);
            _context.SaveChanges();

            return RedirectToAction("ListCarImages", new { page = 1, id = model.CarId });
        }

        [HttpPost]
        public IActionResult DeleteCarImages(List<int> selectedIds)
        {
            if (ModelState.IsValid)
            {
                foreach (var id in selectedIds)
                {
                    var carImages = _context.ImageCars.Find(id);
                    if (carImages != null)
                    {
                        carImages.DeleteFlag = true;
                        _context.ImageCars.Update(carImages);
                    }
                }
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListCarImages", new { page = 1, id = Carid });
        }


        [HttpPost]
        public IActionResult DeleteListCarImages(List<int> selectedIds)
        {
            if (ModelState.IsValid)
            {
                // Tiến hành xóa các bản ghi có ID nằm trong danh sách selectedIds
                foreach (var id in selectedIds)
                {
                    var carImages = _context.ImageCars.Find(id);
                    if (carImages != null)
                    {
                        carImages.DeleteFlag = true;
                        _context.ImageCars.Update(carImages);
                        if (!string.IsNullOrEmpty(carImages.Image))
                        {
                            var imagePath = Path.Combine(Constant.PATH, carImages.Image);
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }
                        }
                    }
                }
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListCarImages", new { page = 1, id = Carid });
        }


    }

}

CarDealers/Areas/Admin/Views/CarImages/CreateCarImages.cshtml
@model CarDealers.Entity.ImageCar
@{
    ViewBag.Title = "Create Car Image";
}

<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("CreateCarImages", "CarImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.CarId)
                    <input type="text" id="CarId" name="CarId" value="@ViewBag.CarId" class="form-control input-rounded"     readonly>
                    @*@Html.TextBoxFor(model => model.CarId, new { @class = "form-control input-rounded", value = "3" })*@

                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.CarId)
                    </div>
                </div>  

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, "Upload Image")
                    <input type="file" id="ImageCars" name="ImageCars" multiple class="form-control-file" />
                    <div style="color: red">
                        @Html.ValidationMessageFor(model => model.Image)
                    </div>
                </div>

                <!-- Add other form fields as needed -->

                <button type="submit" class="btn btn-dark">Create News Type</button>
            }
        </div>
    </div>
    <a style="float:right;margin-right:20px" class="btn btn-dark" href="~/admin/Car/ListCar">Back to list</a>
</div>

CarDealers/Areas/Admin/Views/CarImages/ListCarImages.cshtml
@model IEnumerable<CarDealers.Entity.ImageCar>
@{
    ViewBag.Title = "List Car Image";
}
<style>
    .button-container {
        display: flex;
        gap: 10px; /* Adjust the gap to set the space between links */
        justify-content: center;
    }

    th, td {
        text-align: center; /* Equal width for each column */
    }

    .resized-img {
        width: 100px; /* Set the desired width */
        height: 100px; /* Set the desired height */
    }
</style>





<div class="content-wrap">
    <div class="col-lg-12">
        <form method="post" action="@Url.Action("DeleteListCarImages", "CarImages", new { area = "admin" })">
            <div class="card">
                <div class="table-responsive">
                    <div class="table-wrapper">
                        <div class="table-title">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h2>List images cars</h2>
                                </div>
                                <div class="col-sm-6">
                                    @Html.ActionLink("Create new CarImages", "CreateCarImages", "CarImages", new{ id=@ViewBag.IdCar}, new { @class = "btn btn-dark" })
                                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete selected records?');" />
                                </div>
                            </div>
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" id="selectAll"><br><br>
                                    </th>
                                    <th>Car Name</th>
                                    <th>Image</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var carImage in Model)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="selectedIds" value="@carImage.ImageId" class="checkBox" />
                                            @Html.Hidden("carImagesIds", carImage.ImageId)
                                        </td>
                                        
                                        <td>@carImage.Car.Model</td>
                                        <td>
                                            @if (carImage.Image != null)
                                            {
                                                <img src="@Url.Content("~/"+carImage.Image)" alt="News Image" class="resized-img">
                                            }
                                        </td>
                                        <td class="button-td">
                                            <div class="button-container">
                                                <a href="/admin/CarImages/UpdateCarImages?id=@carImage.ImageId"><input type="button" value="Edit" class="btn btn-dark" /></a>
                                                <a href="/admin/CarImages/DeleteCarImages?id=@carImage.ImageId"><input type="button" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this record?');" /></a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-center" style="margin-top: 20px">
                            <nav aria-label="Page navigation text-center">
                                <ul class="pagination">
                                    @if (ViewBag.PageNumber > 1)
                                    {
                                        <li class="page-item">
                                            <a href="ListCarImages?page=1" class="page-link">&lt&lt</a>
                                        </li>
                                    }

                                    @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize); i++)
                                    {
                                        <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                                            <a href="ListCarImages?page=@i &&id=@ViewBag.IdCar" class="page-link">@i</a>
                                        </li>
                                    }

                                    @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize))
                                    {
                                        <li class="page-item">
                                            <a href="ListCarImages?page=@Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize)" class="page-link">>></a>
                                        </li>
                                    }
                                </ul>
                                
                            </nav>
                        </div>
                        <a style="float:right" class="btn btn-dark" href="~/admin/Car/ListCar">Back to list</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    var selectAllCheckbox = document.getElementById('selectAll');
    var checkBoxes = document.querySelectorAll('.checkBox');

    selectAllCheckbox.addEventListener('change', function () {
        for (var i = 0; i < checkBoxes.length; i++) {
            checkBoxes[i].checked = selectAllCheckbox.checked;
        }
    });
</script>

CarDealers/Areas/Admin/Views/CarImages/UpdateCarImages.cshtml
@model CarDealers.Entity.ImageCar
@{
    ViewBag.Title = "Update Car Image";
}

<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("UpdateCarImages", "CarImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.CarId)
                    @Html.TextBoxFor(model => model.CarId, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                        @Html.ValidationMessageFor(x => x.CarId)
                    </div>
                </div>

                <!-- Display the current logo image, if it exists -->
                <div class="form-group">
                    @if (Model.Image != null)
                    {
                        <label for="currentLogoImage">Current Logo Image</label>
                        <br />
                        <img src="@Url.Content("~/" + Model.Image)" alt="News Image" class="resized-img">
                        <br />
                    }
                    @Html.HiddenFor(model => model.Image)
                </div>

                <!-- Allow the user to upload a new logo image -->
                <div class="form-group">
                    @Html.LabelFor(model => model.Image, "Upload New Logo Image")
                    <input type="file" id="ImageCars" name="ImageCars" class="form-control-file" />
                    <div style="color: red">
                        @Html.ValidationMessageFor(model => model.Image)
                    </div>
                </div>


                @Html.HiddenFor(model => model.ImageId)
                <!-- Add form fields for other properties you want to edit -->

                <button type="submit" class="btn btn-primary">Save Changes</button>
            }
        </div>
        <a style="float:right;" class="btn btn-dark" href="~/admin/Car/ListCar">Back to list</a>
    </div>
</div>