CarDealers/Areas/Admin/Models/CustomerViewModel/CreateCustomerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CarDealers.Areas.Admin.Models.CustomerViewModel
{
    public class CreateCustomerViewModel
    {
        public int CustomerId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public string Dob { get; set; }

        public string? Gender { get; set; }

        public int? Status { get; set; }

        public int? CarId { get; set; }

        public string? Username { get; set; }

        public string? Password { get; set; }

        public string Email { get; set; } = null!;

        public string FullName { get; set; } = null!;

        public string PhoneNumber { get; set; } = null!;

        public string? Address { get; set; }

        public int? Kilometerage { get; set; }

        public string? PlateNumber { get; set; }

        public int CustomerType { get; set; }
    }
}

CarDealers/Areas/Admin/Models/CustomerViewModel/ListCustomerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CarDealers.Areas.Admin.Models.CustomerViewModel
{
    public class ListCustomerViewModel
    {
        public int CustomerId { get; set; }

        public string Email { get; set; } = null!;

        public string FullName { get; set; } = null!;

        public string PhoneNumber { get; set; } = null!;
    }
}

CarDealers/Areas/Admin/Models/CustomerViewModel/UpdateCustomerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CarDealers.Areas.Admin.Models.CustomerViewModel
{
    public class UpdateCustomerViewModel
    {
        public int CustomerId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public string Dob { get; set; }

        public bool? Gender { get; set; }

        public int? Status { get; set; }

        public int? CarId { get; set; }

        public string? Username { get; set; }

        public string? Password { get; set; }

        public string Email { get; set; } = null!;

        public string FullName { get; set; } = null!;

        public string PhoneNumber { get; set; } = null!;

        public string? Address { get; set; }

        public int? Kilometerage { get; set; }

        public string? PlateNumber { get; set; }

        public int CustomerType { get; set; }
    }
}

CarDealers/Areas/Admin/Controllers/CustomerController.cs
using CarDealers.Areas.Admin.Models.CustomerViewModel;
using CarDealers.Entity;
using CarDealers.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.Net;
using System.Net.Mail;
using System.Text;
using static CarDealers.Areas.Admin.Controllers.SendEmailController;

namespace CarDealers.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin/[controller]/[action]")]
    public class CustomerController : CustomController
    {
        private readonly CarDealersContext _context;

        public CustomerController(CarDealersContext context)
        {
            _context = context;
            authorizedRoles = new string[] { Constant.ADMIN_ROLE };
        }

        private const string AllowedChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

        public static string GeneratePassword(int length)
        {
            var random = new Random();
            var password = new StringBuilder(length);

            for (int i = 0; i < length; i++)
            {
                int index = random.Next(AllowedChars.Length);
                password.Append(AllowedChars[index]);
            }

            return password.ToString();
        }

        public IActionResult ListCustomer(int? page, int? pageSize, string Keyword)
        {
			if (!HasAuthorized())
			{
				return RedirectBaseOnPage();
			}
			int defaultPageSize = 5; // Set the number of records per page
            int pageNumber = (page ?? 1); // If no page number is specified, default to 1
            int recordsPerPage = pageSize ?? defaultPageSize;

            //fetch data from database table orders
            var query1 = _context.Customers.Where(x => x.DeleteFlag == false).ToList();

            if (!string.IsNullOrEmpty(Keyword))
            {
                var keywords = Keyword.Trim().ToLower().Split(" ").ToList();
                query1 = query1.Where(u => u.FullName.ToLower().Contains(Keyword.Trim().ToLower())
                || Keyword.Trim().ToLower().Contains(u.FullName.ToLower())
                || keywords.Any(e => u.FullName.ToLower().Contains(e.Trim().ToLower()))).ToList();
            }
            var query = query1.AsQueryable();
            var customers = query.Skip((pageNumber - 1) * (pageSize.HasValue ? pageSize.Value : defaultPageSize)).Take((pageSize.HasValue ? pageSize.Value : defaultPageSize)).ToList();

            var listCustomers = customers.Select(e => new ListCustomerViewModel
            {
                CustomerId = e.CustomerId,
                FullName = e.FullName,
                PhoneNumber = e.PhoneNumber,
                Email = e.Email
            }).ToList();

            // Pass the records and page information to the view
            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = recordsPerPage;
            ViewBag.TotalRecords = query.Count();
            ViewBag.Keyword = Keyword;

            ViewBag.PageSizeList = new List<int> { 5, 10, 20, 50 }; // Add other values as needed

            return View("ListCustomer", listCustomers);
        }

        [HttpGet]
        public IActionResult CreateCustomer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCustomer(CreateCustomerViewModel model, string formaction)
        {
            string customerId = HttpContext.Session.GetString(Constant.LOGIN_USERID_SESSION_NAME);
            var customers = _context.Customers.Where(x => x.DeleteFlag == false).ToList();
            var customersAll = _context.Customers.ToList();
            string originPassword = "";
            Boolean gender = true;

            //check full name
            if (model.FullName == null)
            {
                ModelState.AddModelError("FullName", "Name cannot null.");
                return View(model);
            }
            //check email
            if (model.Email == null)
            {
                ModelState.AddModelError("Email", "Email cannot null.");
                return View(model);
            }
            else if (customersAll.Any(x => x.Email.Equals(model.Email)))
            {
                ModelState.AddModelError("Email", "The Email already exists. Please choose another.");
                return View(model);
            }
            //check phone number
            if (model.PhoneNumber == null)
            {
                ModelState.AddModelError("PhoneNumber", "Phone Number cannot null");
                return View(model);
            }
            //check gender
            if (model.Gender.IsNullOrEmpty())
            {
                ModelState.AddModelError("Gender", "The Gender cannot empty. Please choose a Gender.");
                return View(model);
            }
            //check status
            if (model.Status == null)
            {
                ModelState.AddModelError("Status", "The Status cannot empty. Please choose a Status.");
                return View(model);
            }
            //valid gender
            if (model.Gender.Equals("male"))
            {
                gender = true;
            }
            else
            {
                gender = false;
            }

            //create account
            if (formaction == "CreateCustomerAccount")
            {
                if (customersAll.Where(x => x.CustomerType == 2).Any(x => x.PhoneNumber.Equals(model.PhoneNumber)))
                {
                    ModelState.AddModelError("PhoneNumber", "The Phone Number already exists. Please choose a different PhoneNumber.");
                    return View(model);
                }
                model.CustomerType = 2;
                model.Username = model.Email;
                originPassword = GeneratePassword(7);
                model.Password = HashPassword.GetMD5(originPassword);//Generate Password
            }
            else if (formaction == "SaveInformation")
            {
                model.CustomerType = 1;
            }

            //valid and input model to db
            if (ModelState.IsValid)
            {

                var customer = new Customer
                {
                    Dob = DateTime.ParseExact(model.Dob, "dd-MM-yyyy", CultureInfo.InvariantCulture),
                    Gender = gender,
                    Status = model.Status,
                    Username = model.Username,
                    Password = model.Password,
                    Email = model.Email,
                    FullName = model.FullName,
                    PhoneNumber = model.PhoneNumber,
                    Address = model.Address,
                    CarId = model.CarId,
                    Kilometerage = model.Kilometerage,
                    PlateNumber = model.PlateNumber,
                    CustomerType = model.CustomerType,
                    CreatedBy = customerId != null ? int.Parse(customerId) : null,
                    CreatedOn = DateTime.Now
                };
                await _context.Customers.AddAsync(customer);
                await _context.SaveChangesAsync();


                if (customer.CustomerType == 2)
                {
                    var customerEmail = new EmailModel()
                    {
                        To = customer.Email,
                        Body = originPassword,
                        Subject = "password for our car dealer website"
                    };

                    try
                    {
                        var smtpClient = new SmtpClient("smtp.gmail.com")
                        {
                            Port = 587,
                            Credentials = new NetworkCredential("quochuycode0209@gmail.com", "mfus xank wtah rywh"),
                            EnableSsl = true,
                        };

                        using (var dbContext = new CarDealersContext())
                        {
                            var mailMessage = new MailMessage
                            {
                                From = new MailAddress("quochuycode0209@gmail.com"),
                                Subject = customerEmail.Subject,
                                Body = customerEmail.Body,
                            };
                            mailMessage.To.Add(customer.Email);

                            smtpClient.Send(mailMessage);
                        }

                        ViewBag.Message = "Email sent successfully";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Error = $"Failed to send email: {ex.Message}";
                    }
                }

                return RedirectToAction("ListCustomer");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> DeleteCustomer(int id)
        {
            if (ModelState.IsValid)
            {
                var customer = _context.Customers.Where(x => x.CustomerId == id).FirstOrDefault();
                customer.DeleteFlag = true;
                customer.Status = 0;
                _context.Customers.Update(customer);
                await _context.SaveChangesAsync();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListCustomer");
        }

        [HttpPost]
        public IActionResult DeleteListCustomer(List<int> selectedIds)
        {
            if (ModelState.IsValid)
            {
                string customerId = HttpContext.Session.GetString(Constant.LOGIN_USERID_SESSION_NAME);
                foreach (var id in selectedIds)
                {
                    var customer = _context.Customers.Find(id);
                    if (customer != null)
                    {

CarDealers/Areas/Admin/Views/Customer/CreateCustomer.cshtml
@model CarDealers.Areas.Admin.Models.CustomerViewModel.CreateCustomerViewModel
@{
    ViewBag.Title = "Create Customer";
}
<div class="content-wrap">
    <!-- Include Flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <!-- Include Flatpickr JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("CreateCustomer", "Customer", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, "Full name")
                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.FullName)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email)
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, "Phone number")
                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.PhoneNumber)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dob, "Date of Birth")
                    <input type="text" id="Dob" asp-for="Dob" class="form-control input-rounded" name="Dob" value="">
                    <div style="color: red">
                        @Html.ValidationMessageFor(model => model.Dob)
                    </div>
                </div>

                <script>
                    flatpickr("#Dob", {
                        enableTime: false, // Enable time selection
                        dateFormat: "d-m-Y", // Date and time format
                        // Additional configuration options go here
                    });
                </script>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, "Gender:")
                    <input type="radio" name="Gender" id="gdm" value="male">
                    <label style="margin-right: 10px;" for="gdf">Male</label>

                    <input type="radio" name="Gender" id="option2" value="female">
                    <label for="option2">Female</label>

                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Gender)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, "Status:")
                    <input type="radio" name="Status" id="stt1" value="1">
                    <label style="margin-right: 10px;" for="option1">Normal</label>

                    <input type="radio" name="Status" id="stt2" value="0">
                    <label for="option2">Lock</label>

                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Status)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address)
                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Address)
                    </div>
                </div>

                <!-- Add other form fields as needed -->
                <button type="submit" formaction="~/admin/Customer/ListCustomer" class="btn btn-danger custom-button">Cancel</button>
                <button type="submit" name="formaction" value="SaveInformation" class="btn btn-dark">Save information</button>
                <button type="submit" name="formaction" value="CreateCustomerAccount" class="btn btn-dark">Create Customer Account</button>
            }
        </div>
    </div>
</div>

CarDealers/Areas/Admin/Views/Customer/ListCustomer.cshtml
@model IEnumerable<CarDealers.Areas.Admin.Models.CustomerViewModel.ListCustomerViewModel>
@{
    ViewBag.Title = "List Customer";
}
<style>
    .button-container {
        display: flex;
        gap: 10px; /* Adjust the gap to set the space between links */
        justify-content: center;
    }

    th, td {
        text-align: center; /* Equal width for each column */
    }

    .resized-img {
        width: 100px; /* Set the desired width */
        height: 100px; /* Set the desired height */
    }
</style>
<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            <form method="post" action="@Url.Action("ListCustomer", "Customer", new { area = "admin" })">
                <div class="filter-form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="search-form">
                                <div class="form-group">
                                    <label for="Keyword">Search by name:</label>
                                    <input type="text" class="form-control" id="Keyword" name="Keyword" value="@ViewBag.Keyword">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="hidden" name="pageSize" value="@ViewBag.PageSize" />
                            <button type="submit" class="btn btn-dark">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-lg-12">
        <form method="post" action="@Url.Action("DeleteListCustomer", "Customer", new { area = "admin" })">
            <div class="card">
                <div class="table-responsive">
                    <div class="table-wrapper">
                        <div class="table-title">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h2>Customer List</h2>
                                </div>
                                <div class="col-sm-6">
                                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete selected records?');" />
                                </div>
                            </div>
                        </div>
                        <table class="table student-data-table m-t-20 table table-hover ">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" id="selectAll"><br><br>
                                    </th>
                                    <th>Id</th>
                                    <th>Full Name</th>
                                    <th>Email</th>
                                    <th>Phone Number</th>
                                    <th colspan="2" style="text-align: center;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var customer in Model)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="selectedIds" value="@customer.CustomerId" class="checkBox" />
                                            @Html.Hidden("CustomerId", customer.CustomerId)

                                        </td>
                                        <td>@customer.CustomerId</td>
                                        <td>@customer.FullName</td>
                                        <td>@customer.Email</td>
                                        <td>@customer.PhoneNumber</td>
                                        <td class="button-td">
                                            <div class="button-container">
                                                <a href="/admin/Customer/UpdateCustomer?id=@customer.CustomerId"><input type="button" value="Edit" class="btn btn-dark" /></a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="ml-3">
                                <label for="pageSizeDropdown">Records per page:</label>
                                <select id="pageSizeDropdown" class="form-control" onchange="updatePageSize(this)">
                                    @foreach (var size in ViewBag.PageSizeList)
                                    {
                                        var url = Url.Action("ListCustomer", new { page = 1, pageSize = size, Keyword = ViewBag.Keyword });
                                        <option value="@url" @(size == ViewBag.PageSize ? "selected='selected'" : "")>@size</option>
                                    }
                                </select>
                                <script>
                                    function updatePageSize(selectElement) {
                                        location.href = selectElement.value;
                                    }
                                </script>
                            </div>
                            <div class="d-flex justify-content-center" style="margin-top: 20px">
                                <nav aria-label="Page navigation text-center">
                                    <ul class="pagination">
                                        @if (ViewBag.PageNumber > 1)
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListCustomer", new { page = 1, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Previous</a>
                                            </li>
                                        }

                                        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize); i++)
                                        {
                                            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                                                <a href="@Url.Action("ListCustomer", new { page = i, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">@i</a>
                                            </li>
                                        }

                                        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize))
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListCustomer", new { page = Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize), pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Next</a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <script>
            var selectAllCheckbox = document.getElementById('selectAll');
            var checkBoxes = document.querySelectorAll('.checkBox');

            selectAllCheckbox.addEventListener('change', function () {
                for (var i = 0; i < checkBoxes.length; i++) {
                    checkBoxes[i].checked = selectAllCheckbox.checked;
                }
            });
        </script>
    </div>
</div>

CarDealers/Areas/Admin/Views/Customer/UpdateCustomer.cshtml
@model CarDealers.Areas.Admin.Models.CustomerViewModel.UpdateCustomerViewModel
@{
    ViewBag.Title = "Update Customer";
}
<style>
    .select-sm {
        height: 100px; /* Adjust the height as needed */
        /* Add any other styling you want */
    }

    .btn-group label {
        margin-right: 50px; /* Adjust this value to control the space between the buttons */
    }
</style>
<div class="content-wrap">
    <!-- Include Flatpickr CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <!-- Include Flatpickr JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("UpdateCustomer", "Customer", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, "Full name")
                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control input-rounded", @readonly = "readonly"  })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.FullName)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email)
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-rounded", @readonly = "readonly"  })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, "Phone number")
                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control input-rounded", @readonly = "readonly"  })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.PhoneNumber)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dob, "Date of birth:")
                    <input type="text" id="Dob" asp-for="Dob" class="form-control input-rounded" name="Dob" value="@Model.Dob" readonly>
                    <script>
                        flatpickr("#Dob", {
                            enableTime: false, // Enable time selection
                            dateFormat: "d-m-Y", // Date and time format
                            // Additional configuration options go here
                            onOpen: function (selectedDates, dateStr, instance) {
                                instance.close(); // Close the calendar immediately after opening
                            },
                        });
                    </script>
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Dob)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CustomerType, "Customer type: ")
                    @(Model.CustomerType == 2 ? "Customer" : "Guest")
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.CustomerType)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, "Gender:")
                    <input type="radio" name="Gender" id="option1" value="true" @(Model.Gender == true ? "checked" : "disabled")>
                    <label style="margin-right: 10px;" for="option1">Male</label>

                    <input type="radio" name="Gender" id="option2" value="false" @(Model.Gender == false ? "checked" : "disabled")>
                    <label for="option2">Female</label>

                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Gender)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Status, "Status:")
                    <input type="radio" name="Status" id="option1" value="1" @(Model.Status == 1 ? "checked" : "")>
                    <label style="margin-right: 10px;" for="option1">Normal</label>

                    <input type="radio" name="Status" id="option2" value="0" @(Model.Status == 0 ? "checked" : "")>
                    <label for="option2">Lock</label>

                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Status)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Username)
                    <input type="text" id="Username" name="Username" class="form-control input-rounded" value="@Model.Username" readonly />
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Username)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address)
                    @Html.TextBoxFor(model => model.Address, new { @class = "form-control input-rounded", @readonly = "readonly"  })
                    <div style="color : red">
                        @Html.ValidationMessageFor(model => model.Address)
                    </div>
                </div>

                @Html.HiddenFor(model => model.CustomerId)
                <!-- Add form fields for other properties you want to edit -->
                <button type="submit" formaction="~/admin/Customer/ListCustomer" class="btn btn-danger custom-button">Cancel</button>
                <button type="submit" name="formaction" value="SaveInformation" class="btn btn-dark">Save information</button>
                @if (Model.CustomerType == 1)
                {
                    <button type="submit" name="formaction" value="CreateCustomerAccount" class="btn btn-dark">Create Customer Account</button>
                }
            }
        </div>
    </div>
</div>