CarDealers/Models/TrialDrivingModel/TrialDrivingViewModel.cs
namespace CarDealers.Models.TrialDrivingModel
{
    public class TrialDrivingViewModel
    {
        public string Email { get; set; } = null!;

        public string FullName { get; set; } = null!;

        public string PhoneNumber { get; set; } = null!;

        public int CarId { get; set; }

        public DateTime DateBooking { get; set; }

        public string DriverLicense { get; set; } = null!;

        public string? Request { get; set; }
    }
}

CarDealers/Areas/Admin/Controllers/TrialDrivingController.cs
using CarDealers.Areas.Admin.Models.BookingServiceModel;
using CarDealers.Entity;
using CarDealers.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace CarDealers.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin/[controller]/[action]")]
    public class TrialDrivingController : CustomController
    {
        private readonly CarDealersContext _context;

        public TrialDrivingController(CarDealersContext context)
        {
            _context = context;
            authorizedRoles = new string[] { Constant.ADMIN_ROLE };
        }

        public IActionResult ListTrialDriving(int? page, int? pageSize, string Keyword)
        {
            if (!HasAuthorized())
            {
                return RedirectBaseOnPage();
            }
            int defaultPageSize = 5; // Set a default number of records per page
            int pageNumber = page ?? 1;
            int recordsPerPage = pageSize ?? defaultPageSize;
            var query1 = _context.TrialDrivings.Include(x => x.CarTrail).ThenInclude(x => x.Car).Where(x => x.DeleteFlag == false).ToList();
            if (!string.IsNullOrEmpty(Keyword))
            {
                var keywords = Keyword.Trim().ToLower().Split(" ").ToList();
                query1 = query1.Where(u => u.Email.ToLower().Contains(Keyword.Trim().ToLower()) || Keyword.Trim().ToLower().Contains(u.Email.ToLower()) || keywords.Any(e => u.Email.ToLower().Contains(e.Trim().ToLower()))).ToList();
            }

            var query = query1.AsQueryable();
            var trialDrivings = query.Skip((pageNumber - 1) * (pageSize.HasValue ? pageSize.Value : defaultPageSize)).Take((pageSize.HasValue ? pageSize.Value : defaultPageSize)).ToList();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = recordsPerPage;
            ViewBag.TotalRecords = query.Count();
            ViewBag.Keyword = Keyword;
            ViewBag.PageSizeList = new List<int> { 2, 5, 10, 20, 50 }; // Add other values as needed

            return View(trialDrivings);
        }

        [HttpGet]
        public ActionResult UpdateTrialDriving(int id)
        {
            if (ModelState.IsValid)
            {
                var trialDriving = _context.TrialDrivings.Include(x => x.CarTrail).ThenInclude(x => x.Car).Where(x => x.TrialId == id && x.DeleteFlag == false).FirstOrDefault();

                if (trialDriving == null)
                {
                    return RedirectToAction("RecordNotFound");
                }
                return View(trialDriving);
            }
            return RedirectToAction("RecordNotFound");
        }

        [HttpPost]
        public ActionResult UpdateTrialDriving(TrialDriving model)
        {
            var trialDriving = _context.TrialDrivings
                .Include(x => x.CarTrail)
                .ThenInclude(x => x.Car)
                .Where(x => x.TrialId == model.TrialId && x.DeleteFlag == false)
                .FirstOrDefault();

            if (trialDriving == null)
            {
                return RedirectToAction("RecordNotFound");
            }

            trialDriving.Status = model.Status;
            trialDriving.ModifiedOn = DateTime.Now;
            _context.TrialDrivings.Update(trialDriving);
            _context.SaveChanges();

            string receiver = trialDriving.Email;
            string subject = "Register Trial Driving Successfully";
            string body = $"You have scheduled a test drive for {trialDriving.CarTrail.Car.Model}<br />Time: {trialDriving.DateBooking.ToString("dd/MM/yyyy")}<br />Plate Number: {trialDriving.CarTrail.PlateNumber}<br />Thanks for using our service!";
            SendMail.SendEmail(receiver, subject, body);
            return RedirectToAction("ListTrialDriving");
        }

        [HttpGet]
        public IActionResult DeleteTrialDriving(int id)
        {
            if (ModelState.IsValid)
            {
                var trialDriving = _context.TrialDrivings.Where(x => x.TrialId == id).FirstOrDefault();
                trialDriving.DeleteFlag = true;
                _context.TrialDrivings.Update(trialDriving);
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListTrialDriving");
        }

        [HttpPost]
        public IActionResult DeleteListTrialDriving(List<int> selectedIds)
        {
            if (ModelState.IsValid)
            {
                foreach (var id in selectedIds)
                {
                    var trialDriving = _context.TrialDrivings.Find(id);
                    if (trialDriving != null)
                    {
                        trialDriving.DeleteFlag = true;
                        _context.TrialDrivings.Update(trialDriving);
                    }
                }
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListTrialDriving");
        }
    }
}

CarDealers/Controllers/TrialDrivingController.cs
using CarDealers.Entity;
using CarDealers.Models.TrialDrivingModel;
using CarDealers.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace CarDealers.Controllers
{
    public class TrialDrivingController : CustomController
    {
        private readonly CarDealersContext _context;

        public TrialDrivingController(CarDealersContext context)
        {
            _context = context;
            authorizedRoles = new string[] { Constant.CUSTOMER_ROLE, Constant.GUEST_ROLE };
        }

        public IActionResult Index()
        {
            if (!HasAuthorized())
            {
                return RedirectBaseOnPage();
            }
            ViewBag.FooterText = GetDefaultFooterText();
            ViewBag.Menu = GetDefaultMenu();
            string customerId = HttpContext.Session.GetString(Constant.LOGIN_USERID_SESSION_NAME);
            var customer = _context.Customers.FirstOrDefault(x => x.CustomerId == Converter.ParseInt(customerId));
            var cars = _context.Cars.ToList();
            ViewBag.Cars = cars;
            ViewBag.Customer = customer;
            return View();
        }
        protected List<News> GetDefaultFooterText()
        {
            var footers = _context.News.Include(e => e.NewsType).Where(e => e.DeleteFlag == false && e.NewsType.NewsTypeName.Equals(Constant.FOOTER)).OrderBy(e => e.Order).ToList();
            return footers;
        }
        protected List<News> GetDefaultMenu()
        {
            var menus = _context.News.Include(e => e.NewsType).Where(e => e.DeleteFlag == false && e.NewsType.NewsTypeName.Equals(Constant.MENU)).OrderBy(e => e.Order).ToList();
            return menus;
        }

        [HttpPost]
        public IActionResult RegisterTrial(TrialDrivingViewModel trialDriving)
        {
            using (CarDealersContext context = new CarDealersContext())
            {
                try
                {
                    bool isError = false;
                    //check errror
                    if (string.IsNullOrEmpty(trialDriving.FullName) || string.IsNullOrEmpty(trialDriving.DriverLicense) ||
                        string.IsNullOrEmpty(trialDriving.Email) || string.IsNullOrEmpty(trialDriving.PhoneNumber))
                    {
                        TempData["ErrorMessage"] = "Please fill all information.";
                        isError = true;
                    }
                    else
                    {
                        if (!Validation.CheckFullName(trialDriving.FullName))
                        {
                            TempData["ErrorMessageFullName"] = "Please check fullname again";
                            isError = true;
                        }
                        if (!Validation.CheckPhone(trialDriving.PhoneNumber))
                        {
                            TempData["ErrorMessagePhoneNumber"] = "Please check phonenumber again";
                            isError = true;
                        }
                        if (!Validation.CheckEmail(trialDriving.Email))
                        {
                            TempData["ErrorMessageEmail"] = "Email must correct with format";
                            isError = true;
                        }
                        if (!Validation.CheckDriverLicense(trialDriving.DriverLicense))
                        {
                            TempData["ErrorMessageDriverLicense"] = "Please check driver license again";
                            isError = true;
                        }
                        if (!Validation.CheckBookingDate(trialDriving.DateBooking))
                        {
                            TempData["ErrorMessageDateBooking"] = "Please check date booking again";
                            isError = true;
                        }
                    }
                    if (!isError)
                    {
                        var listCarTrial = _context.TrialDrivings.Include(x => x.CarTrail)
                            .Where(x => x.DateBooking == trialDriving.DateBooking && x.CarTrail.CarId == trialDriving.CarId)
                            .Select(x => x.CarTrailId).ToList();
                        var carTrial = new CarTrial();
                        if (listCarTrial == null)
                        {
                            carTrial = _context.CarTrials.FirstOrDefault(carTrial => carTrial.Status == 1 && carTrial.CarId == trialDriving.CarId);
                        }
                        else
                        {
                            carTrial = _context.CarTrials.FirstOrDefault(carTrial => !listCarTrial.Any(x => x == carTrial.CarTrialId) && carTrial.Status == 1 && carTrial.CarId == trialDriving.CarId);
                        }
                        if (carTrial != null)
                        {
                            var newTrialDriving = new TrialDriving()
                            {
                                Email = trialDriving.Email,
                                FullName = trialDriving.FullName,
                                PhoneNumber = trialDriving.PhoneNumber,
                                CarTrailId = carTrial.CarTrialId,
                                DateBooking = trialDriving.DateBooking,
                                DriverLicense = trialDriving.DriverLicense,
                                Request = trialDriving.Request,
                                Status = 0,
                                DeleteFlag = false,
                                CreatedOn = DateTime.Now
                            };
                            _context.TrialDrivings.Add(newTrialDriving);
                            _context.SaveChanges();
                            TempData["SuccessMessage"] = "Submited successfully!";

                            string receiver = trialDriving.Email;
                            string subject = "Schedule a trial driving";
                            var carName = _context.Cars.FirstOrDefault(x => x.CarId == carTrial.CarId);
                            string body = $"You have scheduled a test drive for {carName.Model}<br />Time: {trialDriving.DateBooking.ToString("dd/MM/yyyy")}<br />Please wait for a confirmation email from us."; 
                            SendMail.SendEmail(receiver, subject, body);
                        }
                        else
                        {
                            TempData["ErrorFullMessage"] = "This car model is fully booked on the day you booked";
                            isError = true;
                        }
                    }
                    // if has error
                    if (isError)
                    {
                        var cars = _context.Cars.ToList();
                        ViewBag.Cars = cars;
                        ViewBag.FooterText = GetDefaultFooterText();
                        ViewBag.Menu = GetDefaultMenu();
                        return View("Index", trialDriving);
                    }
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return Redirect(Constant.TRIAL_PAGE);
        }

    }
}

CarDealers/Areas/Admin/Views/TrialDriving/ListTrialDriving.cshtml
@model IEnumerable<CarDealers.Entity.TrialDriving>
@{
    ViewBag.Title = "List Trial Driving";
}
<style>
    .button-container {
        display: flex;
        gap: 10px; /* Adjust the gap to set the space between links */
        justify-content: center;
    }

    th, td {
        text-align: center; /* Equal width for each column */
    }

    .resized-img {
        width: 100px; /* Set the desired width */
        height: 100px; /* Set the desired height */
    }

    }
</style>
<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            <form method="post" action="@Url.Action("ListTrialDriving", "TrialDriving", new { area = "admin" })">
                <div class="filter-form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="search-form">
                                <div class="form-group">
                                    <label for="Keyword">Search:</label>
                                    <input type="text" class="form-control" id="Keyword" name="Keyword" value="@ViewBag.Keyword">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="hidden" name="pageSize" value="@ViewBag.PageSize" />
                            <button type="submit" class="btn btn-dark">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="content-wrap">
    <div class="col-lg-12">
        <form method="post" action="@Url.Action("DeleteListTrialDriving", "TrialDriving", new { area = "admin" })">
            <div class="card">

                <div class="table-responsive">
                    <div class="table-wrapper">
                        <div class="table-title">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h2>Manage Trial Driving</h2>
                                </div>
                                <div class="col-sm-6">                                   
                                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete selected records?');" />
                                </div>
                            </div>
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" id="selectAll"><br><br>
                                    </th>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone Number</th>
                                    <th>Model</th>
                                    @*<th>Plate Number</th>*@
                                    @*<th>Car Status</th>*@
                                    <th>Date Booking</th>
                                    @*<th>Driver License</th>*@
                                    @*<th>Request</th>*@
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var trialDriving in Model)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="selectedIds" value="@trialDriving.TrialId" class="checkBox" />
                                            @Html.Hidden("TrialDrivingIds", trialDriving.TrialId)
                                        </td>
                                        <td>@trialDriving.TrialId</td>
                                        <td>@trialDriving.FullName</td>
                                        <td>@trialDriving.Email</td>
                                        <td>@trialDriving.PhoneNumber</td>
                                        <td>@trialDriving.CarTrail.Car.Model</td>
                                        @*<td>@trialDriving.CarTrail.PlateNumber</td>*@
                                        @*<td>@trialDriving.CarTrail.Status</td>*@
                                        <td>@trialDriving.DateBooking.ToString("dd/MM/yyyy")</td>
                                        @*<td>@trialDriving.DriverLicense</td>*@
                                        @*<td>@trialDriving.Request</td>*@
                                        <td>@trialDriving.Status</td>
                                        <td class="button-td">
                                            <div class="button-container">
                                                <a href="/admin/TrialDriving/UpdateTrialDriving?id=@trialDriving.TrialId"><input type="button" value="Edit" class="btn btn-dark" /></a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="ml-3">
                                <label for="pageSizeDropdown">Records per page:</label>
                                <select id="pageSizeDropdown" class="form-control" onchange="updatePageSize(this)">
                                    @foreach (var size in ViewBag.PageSizeList)
                                    {
                                        var url = Url.Action("ListTrialDriving", new { page = 1, pageSize = size, Keyword = ViewBag.Keyword });
                                        <option value="@url" @(size == ViewBag.PageSize ? "selected='selected'" : "")>@size</option>
                                    }
                                </select>
                                <script>
                                    function updatePageSize(selectElement) {
                                        location.href = selectElement.value;
                                    }
                                </script>
                            </div>
                            <div class="d-flex justify-content-center" style="margin-top: 20px">
                                <nav aria-label="Page navigation text-center">
                                    <ul class="pagination">
                                        @if (ViewBag.PageNumber > 1)
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListTrialDriving", new { page = 1, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Previous</a>
                                            </li>
                                        }

                                        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize); i++)
                                        {
                                            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                                                <a href="@Url.Action("ListTrialDriving", new { page = i, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">@i</a>
                                            </li>
                                        }

                                        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize))
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListTrialDriving", new { page = Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize), pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Next</a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <script>
            var selectAllCheckbox = document.getElementById('selectAll');
            var checkBoxes = document.querySelectorAll('.checkBox');

            selectAllCheckbox.addEventListener('change', function () {
                for (var i = 0; i < checkBoxes.length; i++) {
                    checkBoxes[i].checked = selectAllCheckbox.checked;
                }
            });
        </script>
    </div>
</div>

CarDealers/Areas/Admin/Views/TrialDriving/UpdateTrialDriving.cshtml
@model CarDealers.Entity.TrialDriving
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewBag.Title = "Update Trial Driving";
}
<style>
    .resized-img {
        width: 155px; /* Set the desired width */
        height: 155px; /* Set the desired height */
    }

    .select-sm {
        height: 100px; /* Adjust the height as needed */
        /* Add any other styling you want */
    }

    .btn-group label {
        margin-right: 50px; /* Adjust this value to control the space between the buttons */
    }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Include Flatpickr CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<!-- Include Flatpickr JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<div class="content-wrap">
    <div class="row">
        <div class="col-lg-12">
            @using (Html.BeginForm("UpdateTrialDriving", "TrialDriving", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.TrialId)
                <div class="card">
                    <!-- Read-only fields -->
                    <div class="form-group">
                        @Html.LabelFor(model => model.FullName)
                        @Html.TextBoxFor(model => model.FullName, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email)
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber)
                        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CarTrail.Car.Model)
                        @Html.TextBoxFor(model => model.CarTrail.Car.Model, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CarTrail.PlateNumber)
                        @Html.TextBoxFor(model => model.CarTrail.PlateNumber, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        <label>Car Trial Status</label>
                        @Html.TextBoxFor(model => model.CarTrail.Status, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateBooking)
                        <input type="text" id="DateBooking" asp-for="DateBooking" class="form-control input-rounded" name="DateBooking" value="@Model.DateBooking" readonly="readonly">
                        <script>
                            flatpickr("#DateBooking", {
                                enableTime: false, // Enable time selection
                                dateFormat: "d-m-Y", // Date format
                            });
                            document.querySelector('.flatpickr').setAttribute('readonly', 'readonly');
                        </script>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DriverLicense)
                        @Html.TextBoxFor(model => model.DriverLicense, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Request)
                        @Html.TextBoxFor(model => model.Request, new { @class = "form-control input-rounded", @readonly = "readonly" })
                    </div>
                    <div class="form-group" id="statusContainer">
                        @Html.LabelFor(model => model.Status)
                        <br />
                        <input type="radio" name="Status" id="option1" value="1" @(Model.Status == 1 ? "checked" : "") @(Model.Status == 1 ? "disabled" : "")>
                        <label style="margin-right: 10px;" for="option1">Active</label>

                        <input type="radio" name="Status" id="option2" value="0" @(Model.Status == 0 ? "checked" : "")>
                        <label for="option2">Inactive</label>

                        <div style="color : red">
                            @Html.ValidationMessageFor(model => model.Status)
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" formaction="~/admin/TrialDriving/ListTrialDriving" class="btn btn-danger custom-button">Cancel</button>
                        <button type="submit" class="btn btn-dark custom-button">Update Trial Driving</button>
                    </div>
                </div>
            }
        </div>

    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var statusContainer = document.getElementById("statusContainer");
        var radioOption1 = document.getElementById("option1");
        var radioOption2 = document.getElementById("option2");

        var initialStatus = @Model.Status;

        if (initialStatus === 1) {
            radioOption2.disabled = true;
        }

        statusContainer.addEventListener("click", function () {
            var currentStatus = parseInt(document.querySelector('input[name="Status"]:checked').value);

            if (initialStatus === 1 && currentStatus === 0) {
                radioOption2.checked = false;
                alert("Cannot switch from Active to Inactive.");
            }
        });
    });
</script>