CarDealers/Areas/Admin/Controllers/FuelController.cs
using CarDealers.Entity;
using CarDealers.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;


namespace CarDealers.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin/[controller]/[action]")]
    public class FuelController : CustomController
    {
        private readonly CarDealersContext _context;

        public FuelController(CarDealersContext context)
        {
            _context = context;
            authorizedRoles = new string[] { Constant.ADMIN_ROLE };
        }

        public IActionResult ListFuel(int? page, int? pageSize, string Keyword)
        {
			if (!HasAuthorized())
			{
				return RedirectBaseOnPage();
			}
			int defaultPageSize = 5; // Set a default number of records per page
            int pageNumber = page ?? 1;
            int recordsPerPage = pageSize ?? defaultPageSize;
            var query1 = _context.FuelTypes.Where(x => x.DeleteFlag == false).ToList();
            if (!string.IsNullOrEmpty(Keyword))
            {
                var keywords = Keyword.Trim().ToLower().Split(" ").ToList();
                query1 = query1.Where(u => u.FuelTypeName.ToLower().Contains(Keyword.Trim().ToLower()) || Keyword.Trim().ToLower().Contains(u.FuelTypeName.ToLower()) || keywords.Any(e => u.FuelTypeName.ToLower().Contains(e.Trim().ToLower()))).ToList();
            }

            var query = query1.AsQueryable();
            var fuels = query.Skip((pageNumber - 1) * (pageSize.HasValue ? pageSize.Value : defaultPageSize)).Take((pageSize.HasValue ? pageSize.Value : defaultPageSize)).ToList();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = recordsPerPage;
            ViewBag.TotalRecords = query.Count();
            ViewBag.Keyword = Keyword;
            ViewBag.PageSizeList = new List<int> { 2, 5, 10, 20, 50 }; // Add other values as needed

            return View(fuels);
		}
            
        public ActionResult CreateFuel() {
            return View();
        }

        [HttpPost]
        public IActionResult CreateFuel(FuelType model) {
            if(ModelState.IsValid)
            {
                var fuels = _context.FuelTypes.Where(x => x.DeleteFlag == false).ToList();
                if (fuels.Any(x => x.FuelTypeName.Equals(model.FuelTypeName))){

                    ModelState.AddModelError("FuelTypeName", "The name already exists. Please choose a different name.");
                    return View(model);
                }

                var fuel = new FuelType { FuelTypeName = model.FuelTypeName };
                _context.FuelTypes.Add(fuel);
                _context.SaveChanges();
            }
            return RedirectToAction("ListFuel");
        }

        [HttpGet]
        public IActionResult DeleteFuel(int id)
        {
            if (ModelState.IsValid)
            {
                var fuel = _context.FuelTypes.Where(x => x.FuelTypeId == id).FirstOrDefault();
                fuel.DeleteFlag = true;
                _context.FuelTypes.Update(fuel);
                _context.SaveChanges();
            }
            else {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListFuel");
        }

        [HttpGet]
        public ActionResult UpdateFuel(int id) {
            if (ModelState.IsValid) {
                var fuel = _context.FuelTypes.Where(x => x.FuelTypeId == id && x.DeleteFlag == false).FirstOrDefault();
                
                if (fuel == null) {
                    return RedirectToAction("RecordNotFound");
                }
                return View(fuel);
            }
            return RedirectToAction("RecordNotFound");
        }
        [HttpPost]
        public ActionResult UpdateFuel(FuelType model) {
            if (ModelState.IsValid) {
                var fuels = _context.FuelTypes.Where(x => x.DeleteFlag == false).ToList();
                var fuel = fuels.Where(x => x.FuelTypeId == model.FuelTypeId).FirstOrDefault();

                if(fuel == null) 
                {
                    return RedirectToAction("RecordNotFound");
                }

                if (fuels.Any(x => x.FuelTypeName.Equals(model.FuelTypeName) && x.FuelTypeId != model.FuelTypeId))
                {
                    ModelState.AddModelError("FuelName", "The name already exists. Please choose a different name.");
                    return View(model);
                }

                fuel.FuelTypeName = model.FuelTypeName;
                _context.FuelTypes.Update(fuel);
                _context.SaveChanges();
                
            }
            return RedirectToAction("ListFuel");
        }

        [HttpPost]
        public IActionResult DeleteListFuelType(List<int> selectedIds)
        {
            if (ModelState.IsValid)
            {
                foreach (var id in selectedIds)
                {
                    var fuelType = _context.FuelTypes.Find(id);
                    if (fuelType != null)
                    {
                        fuelType.DeleteFlag = true;
                        _context.FuelTypes.Update(fuelType);
                    }
                }
                _context.SaveChanges();
            }
            else
            {
                return RedirectToAction("RecordNotFound");
            }
            return RedirectToAction("ListFuel");
        }
        
    }
}

CarDealers/Areas/Admin/Views/Fuel/CreateFuel.cshtml
@model CarDealers.Entity.FuelType
@{
    ViewBag.Title = "Create Fuel Type";
}
<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("CreateFuel", "Fuel", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(model => model.FuelTypeName)
                    @Html.TextBoxFor(model => model.FuelTypeName, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                    @Html.ValidationMessageFor(model => model.FuelTypeName)
                    </div>
                </div>

                <!-- Add other form fields as needed -->

                <button type="submit" class="btn btn-dark">Create Fuel</button>
            }
        </div>
    </div>
</div>

CarDealers/Areas/Admin/Views/Fuel/ListFuel.cshtml
@model IEnumerable<CarDealers.Entity.FuelType>
@{
    ViewBag.Title = "List Fuel Type";
}
<style>
    .button-container {
        display: flex;
        gap: 10px; /* Adjust the gap to set the space between links */
        justify-content: center;
    }

    th, td {
        text-align: center; /* Equal width for each column */
    }

    .resized-img {
        width: 100px; /* Set the desired width */
        height: 100px; /* Set the desired height */
    }

    }
</style>
<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            <form method="post" action="@Url.Action("ListFuel", "Fuel", new { area = "admin" })">
                <div class="filter-form">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="search-form">
                                <div class="form-group">
                                    <label for="Keyword">Search:</label>
                                    <input type="text" class="form-control" id="Keyword" name="Keyword" value="@ViewBag.Keyword">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="hidden" name="pageSize" value="@ViewBag.PageSize" />
                            <button type="submit" class="btn btn-dark">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="content-wrap">
    <div class="col-lg-12">
        <form method="post" action="@Url.Action("DeleteListFuelType", "Fuel", new { area = "admin" })">
            <div class="card">

                <div class="table-responsive">
                    <div class="table-wrapper">
                        <div class="table-title">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h2>Manage Fuel Type Car</h2>
                                </div>
                                <div class="col-sm-6">
                                    @Html.ActionLink("Create new fuel", "CreateFuel", "Fuel", null, new { @class = "btn btn-dark" })
                                    <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete selected records?');" />
                                </div>
                            </div>
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <input type="checkbox" id="selectAll"><br><br>
                                    </th>
                                    <th>Id</th>
                                    <th>Fuel Name</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var fuel in Model)
                                {
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="selectedIds" value="@fuel.FuelTypeId" class="checkBox" />
                                            @Html.Hidden("FuelTypeIds", fuel.FuelTypeId)
                                        </td>
                                        <td>@fuel.FuelTypeId</td>
                                        <td>@fuel.FuelTypeName</td>

                                        <td class="button-td">
                                            <div class="button-container">
                                                <a href="/admin/Fuel/UpdateFuel?id=@fuel.FuelTypeId"><input type="button" value="Edit" class="btn btn-dark" /></a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="ml-3">
                                <label for="pageSizeDropdown">Records per page:</label>
                                <select id="pageSizeDropdown" class="form-control" onchange="updatePageSize(this)">
                                    @foreach (var size in ViewBag.PageSizeList)
                                    {
                                        var url = Url.Action("ListFuel", new { page = 1, pageSize = size, Keyword = ViewBag.Keyword });
                                        <option value="@url" @(size == ViewBag.PageSize ? "selected='selected'" : "")>@size</option>
                                    }
                                </select>
                                <script>
                                    function updatePageSize(selectElement) {
                                        location.href = selectElement.value;
                                    }
                                </script>
                            </div>
                            <div class="d-flex justify-content-center" style="margin-top: 20px">
                                <nav aria-label="Page navigation text-center">
                                    <ul class="pagination">
                                        @if (ViewBag.PageNumber > 1)
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListFuel", new { page = 1, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Previous</a>
                                            </li>
                                        }

                                        @for (int i = 1; i <= Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize); i++)
                                        {
                                            <li class="page-item @(ViewBag.PageNumber == i ? "active" : "")">
                                                <a href="@Url.Action("ListFuel", new { page = i, pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">@i</a>
                                            </li>
                                        }

                                        @if (ViewBag.PageNumber < Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize))
                                        {
                                            <li class="page-item">
                                                <a href="@Url.Action("ListFuel", new { page = Math.Ceiling((decimal)ViewBag.TotalRecords / ViewBag.PageSize), pageSize = ViewBag.PageSize, Keyword = ViewBag.Keyword})" class="page-link">Next</a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <script>
            var selectAllCheckbox = document.getElementById('selectAll');
            var checkBoxes = document.querySelectorAll('.checkBox');

            selectAllCheckbox.addEventListener('change', function () {
                for (var i = 0; i < checkBoxes.length; i++) {
                    checkBoxes[i].checked = selectAllCheckbox.checked;
                }
            });
        </script>
    </div>
</div>

CarDealers/Areas/Admin/Views/Fuel/UpdateFuel.cshtml
@model CarDealers.Entity.FuelType
@{
    ViewBag.Title = "Update Fuel Type";
}
<div class="content-wrap">
    <div class="col-lg-12">
        <div class="card">
            @using (Html.BeginForm("UpdateFuel", "Fuel", new { id = Model.FuelTypeId }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(model => model.FuelTypeName)
                    @Html.TextBoxFor(model => model.FuelTypeName, new { @class = "form-control input-rounded" })
                    <div style="color : red">
                    @Html.ValidationMessageFor(x => x.FuelTypeName)
                    </div>
                </div>
                @Html.HiddenFor(model => model.FuelTypeId)
                <!-- Add form fields for other properties you want to edit -->

                <button type="submit" class="btn btn-dark">Save Changes</button>
            }
        </div>
    </div>
</div>